export const CAT_ICONS = {
  ADD: 'add',
  DASHBOARD: 'dashboard',
  LAUNDRY: 'laundry',
  INVENTORY: 'inventory',
  USERS: 'users',
  CONFIG: 'config',
  INFO: 'info',
  ORDER: 'order',
  FILE: 'file',
  CLOSE: 'close',
  SEARCH: 'search',
  DELETE: 'delete',
  EDIT: 'edit',
  MONEY: 'money',
  TIME: 'time',
  ARROW_DOWN: 'arrow-down',
} as const
